name: Website - Production
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build Website
    runs-on: ubuntu-latest
    steps:
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          
      - name: Checkout website source
        id: checkout-master
        uses: actions/checkout@v2
        
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: pelican-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            pelican-
            
      - name: Install Pelican and Dependencies
        run: |
          python -m pip install -U pip 
          pip install -r requirements.txt
      
      - name: Install Pelican plugins
        uses: actions/checkout@v2
        with:
          repository: 'getpelican/pelican-plugins'
          path: 'plugins'
        
      - name: Install Pelican themes
        uses: actions/checkout@v2
        with:
          repository: 'getpelican/pelican-themes'
          path: 'themes'
          
      - name: Generate website
        id: generate-website
        run: |
          pelican content --output output --settings publishconf.py
          
      - name: Package the website artifact
        uses: actions/upload-artifact@v2
        with:
          name: website-output
          path: |
            output/
          retention-days: 1
          
  deploy:
    name: Deploy Website
    runs-on: ubuntu-latest
    needs: [build]
   
    permissions:
      contents: 'read'
      id-token: 'write'
      
    steps:   
      - name: Get website artifact
        uses: actions/download-artifact@v2
        with:
          name: website-output
          path: web-files/
      
      - name: Set website file ownership
        run: |
          sudo chown -R www-data:www-data web-files/*
          
      - name: Setup Google Authorization
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: '${{ secrets.WORKLOAD_ID_PROVIDER }}'
          service_account: '${{ secrets.DEPLOY_SERVICE_ACCOUNT }}'
        
      - name: 'Set up gcloud CLI'
        uses: 'google-github-actions/setup-gcloud@v0'
          
      - name: 'Copy Website files to instance'
        run: |
          gcloud compute scp --recurse --ssh-key-expire-after=5m --zone=northamerica-northeast2-a web-files/* webserver:/var/www/artificialbelligerence.com/htdocs
      
      - name: 'Remove runner metadata'
        env:
          CURRENT_FILE: './ssh_current_keys'
          UPDATE_FILE: './ssh_update_keys'
        run: |
          echo "$(gcloud compute instances describe webserver --zone=northamerica-northeast2-a --format='json(metadata.items[])' | jq -rc '.metadata.items[] | select(.key=="ssh-keys") | .value')" > ${{ env.CURRENT_FILE }}
          echo "$RUNNER_NAME"
          echo "${{ env.RUNNER_NAME }}"
          sed "/^${{ RUNNER_NAME }}/d" ${{ env.CURRENT_FILE }} > ${{ env.UPDATE_FILE }}
          gcloud compute instances add-metadata webserver --zone=northamerica-northeast2-a --metadata-from-file=ssh-keys=${{ env.UPDATE_FILE }}
          rm -f ${{ env.CURRENT_FILE }}
          rm -f ${{ env.UPDATE_FILE }}
